spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrs_user
    username: root
    password: root
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update    
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: WARN
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
